---
# Base veda realm configuration
# IDP and auth flows are defined in environment-specific files (veda.dev.yaml, veda.staging.yaml, etc.)
enabled: true
realm: veda
displayName: Applications
displayNameHtml: VEDA Ecosystem
loginTheme: veda

clients:
  - clientId: account-console
    name: Account Console
    rootUrl: $(env:ACCOUNT_CONSOLE_URL)
    publicClient: true
    protocol: openid-connect
    standardFlowEnabled: true
    fullScopeAllowed: true
    attributes:
      post.logout.redirect.uris: "+"
    redirectUris:
      - $(env:ACCOUNT_CONSOLE_URL)/*
    webOrigins:
      - $(env:ACCOUNT_CONSOLE_URL)
    defaultClientScopes:
      - web-origins
      - profile
      - email
      - roles

  - clientId: stac
    name: STAC Catalog
    rootUrl: $(env:STAC_CLIENT_URL)
    publicClient: true
    attributes:
      post.logout.redirect.uris: "+"
    redirectUris:
      - $(env:STAC_CLIENT_URL)/*
    webOrigins:
      - "+"
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete

  - clientId: airflow-stac-etl
    name: Airflow STAC ETL
    secret: $(env:AIRFLOW_STAC_ETL_CLIENT_SECRET)
    publicClient: false
    attributes: {}
    protocol: openid-connect
    fullScopeAllowed: true
    standardFlowEnabled: false
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    optionalClientScopes:
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete
    defaultClientScopes:
      - roles

  - clientId: ingest-api
    name: STAC Ingest API
    rootUrl: $(env:INGEST_API_CLIENT_URL)
    publicClient: true
    attributes:
      "access.token.lifespan": "3600"
      post.logout.redirect.uris: "+"
    redirectUris:
      - $(env:INGEST_API_CLIENT_URL)/*
    webOrigins:
      - "+"
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete

  - clientId: airflow-ingest-api-etl
    name: Airflow Ingest API ETL
    secret: $(env:AIRFLOW_INGEST_API_ETL_CLIENT_SECRET)
    publicClient: false
    attributes: {}
    protocol: openid-connect
    fullScopeAllowed: true
    standardFlowEnabled: false
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    optionalClientScopes:
      - stac:item:create
      - stac:item:update
      - stac:item:delete
      - stac:collection:create
      - stac:collection:update
      - stac:collection:delete
    defaultClientScopes:
      - roles

  - clientId: ingest-ui
    name: Ingest UI
    rootUrl: $(env:INGEST_UI_CLIENT_URL)
    secret: $(env:INGEST_UI_CLIENT_SECRET)
    publicClient: false
    attributes:
      post.logout.redirect.uris: "+"
    redirectUris:
      - $(env:INGEST_UI_CLIENT_URL)/*
    webOrigins:
      - $(env:INGEST_UI_CLIENT_URL)
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email
      - dataset:create
      - dataset:update

  - clientId: veda-airflow
    name: Airflow
    rootUrl: $(env:AIRFLOW_CLIENT_URL)
    secret: $(env:VEDA_AIRFLOW_CLIENT_SECRET)
    publicClient: false
    attributes:
      post.logout.redirect.uris: "+"
    redirectUris:
      - $(env:AIRFLOW_CLIENT_URL)/*
    webOrigins:
      - $(env:AIRFLOW_CLIENT_URL)
    protocol: openid-connect
    fullScopeAllowed: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - basic
      - email

  - clientId: jupyterhub
    name: JupyterHub
    rootUrl: $(env:JUPYTERHUB_CLIENT_URL)
    secret: $(env:JUPYTERHUB_CLIENT_SECRET)
    publicClient: false
    attributes:
      post.logout.redirect.uris: $(env:JUPYTERHUB_CLIENT_URL)/*
    redirectUris:
      - $(env:JUPYTERHUB_CLIENT_URL)/hub/oauth_callback
    webOrigins:
      - $(env:JUPYTERHUB_CLIENT_URL)
    protocol: openid-connect
    fullScopeAllowed: true
    defaultClientScopes:
      - profile
      - roles
      - basic
      - email
      - groups
    protocolMappers:
      - name: preferred_username
        protocol: openid-connect
        protocolMapper: oidc-usermodel-property-mapper
        config:
          user.attribute: username
          claim.name: preferred_username
          jsonType.label: String
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
      - name: groups
        protocol: openid-connect
        protocolMapper: oidc-group-membership-mapper
        config:
          full.path: "false"
          id.token.claim: "true"
          access.token.claim: "true"
          claim.name: groups
          userinfo.token.claim: "true"
      - name: client-roles-claim
        protocol: openid-connect
        protocolMapper: oidc-usermodel-client-role-mapper
        config:
          access.token.claim: "true"
          userinfo.token.claim: "true"
          id.token.claim: "true"
          claim.name: roles
          jsonType.label: String
          multivalued: "true"
          usermodel.clientRoleMapping.clientId: jupyterhub
          usermodel.clientRoleMapping.rolePrefix: ""
roles:
  client:
    stac:
      - name: Admin
        description: Can create, update and delete STAC collections and items
      - name: Editor
        description: Can create and update STAC collections and items
    ingest-api:
      - name: Admin
        description: Can create, update and delete STAC collections and items
      - name: Editor
        description: Can create and update STAC collections and items
    ingest-ui:
      - name: Editor
        description: Can initiate and update dataset ingests
    veda-airflow:
      - name: Admin
        description: Full administrative access to Airflow
      - name: Reader
        description: Read-only access to Airflow
      - name: Launcher
    jupyterhub:
      - name: Admin
        description: Can use the JupyterHub Admin Panel
      - name: CPU:XS
        description: Access to extra small instances (~1.9GB RAM)
      - name: CPU:S
        description: Access to small instances (~3.7GB RAM)
      - name: CPU:M
        description: Access to medium instances (~7.4GB RAM)
      - name: CPU:L
        description: Access to large instances (~14.8GB RAM)
      - name: CPU:XL
        description: Access to extra large instances (~29.7GB RAM)
      - name: CPU:XXL
        description: Access to extra extra large instances (~60.6GB RAM)
      - name: CPU:XXXL
        description: Access to extra extra extra large instances (~121GB RAM)
      - name: GPU:T4
        description: Access to T4 GPU instances (1 T4 GPU)


clientScopeMappings:
  stac:
    - clientScope: stac:item:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:delete
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:delete
      roles:
        - Admin
  ingest-api:
    - clientScope: stac:item:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:item:delete
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:create
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:update
      roles:
        - Admin
        - Editor
    - clientScope: stac:collection:delete
      roles:
        - Admin
  ingest-ui:
    - clientScope: dataset:create
      roles:
        - Editor
    - clientScope: dataset:update
      roles:
        - Editor

clientScopes:
  - name: stac:item:create
    description: Create STAC items
    protocol: openid-connect
  - name: stac:item:update
    description: Update STAC items
    protocol: openid-connect
  - name: stac:item:delete
    description: Delete STAC items
    protocol: openid-connect
  - name: stac:collection:create
    description: Create STAC collections
    protocol: openid-connect
  - name: stac:collection:update
    description: Update STAC collections
    protocol: openid-connect
  - name: stac:collection:delete
    description: Delete STAC collections
    protocol: openid-connect
  - name: dataset:create
    description: Ingest new datasets
    protocol: openid-connect
  - name: dataset:update
    description: Update existing datasets
    protocol: openid-connect
  - name: groups
    description: Group membership information
    protocol: openid-connect
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "true"
    protocolMappers:
      - name: groups
        protocol: openid-connect
        protocolMapper: oidc-group-membership-mapper
        consentRequired: false
        config:
          full.path: "false"
          id.token.claim: "true"
          access.token.claim: "true"
          claim.name: groups
          userinfo.token.claim: "true"

groups:
  - name: System Administrators
    clientRoles:
      stac:
        - Admin
      ingest-api:
        - Admin
      ingest-ui:
        - Editor

  - name: Developers
    clientRoles:
      stac:
        - Admin
      ingest-api:
        - Admin
      ingest-ui:
        - Editor

  - name: Data Editors
    clientRoles:
      stac:
        - Editor
      ingest-api:
        - Editor
      ingest-ui:
        - Editor

  - name: VEDA Airflow Admins
    clientRoles:
      veda-airflow:
        - Admin
  - name: VEDA Airflow Viewers
    clientRoles:
      veda-airflow:
        - Reader
  - name: VEDA Airflow DAG Launchers
    clientRoles:
      veda-airflow:
        - Launcher
  
  - name: JupyterHub Admin
    clientRoles:
      jupyterhub:
        - Admin
  - name: JupyterHub User
    clientRoles:
      jupyterhub:
        - CPU:XS
        - CPU:S
        - CPU:M
        - CPU:L
        - CPU:XL
        - CPU:XXL
        - CPU:XXXL
  - name: JupyterHub Basic User
    clientRoles:
      jupyterhub:
        - CPU:XS
        - CPU:S
        - CPU:M
  - name: JupyterHub GPU User
    clientRoles:
      jupyterhub:
        - GPU:T4

users:
  - username: service-account-airflow-stac-etl
    emailVerified: true
    enabled: true
    serviceAccountClientId: airflow-stac-etl
    clientRoles:
      stac:
      - Admin
  - username: service-account-airflow-ingest-api-etl
    emailVerified: true
    enabled: true
    serviceAccountClientId: airflow-ingest-api-etl
    clientRoles:
      ingest-api:
      - Admin

# Post-broker login flow for email whitelist checking
# Only enforced when SSO_EMAIL_WHITELIST env var is set on the Keycloak server
authenticationFlows:
  - alias: "Email Whitelist Check"
    description: "Checks user email against SSO_EMAIL_WHITELIST env var"
    providerId: basic-flow
    topLevel: true
    builtIn: false
    authenticationExecutions:
      - authenticator: email-whitelist
        authenticatorFlow: false
        requirement: REQUIRED
        priority: 10
